# Generated by Django 3.2.2 on 2021-05-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210512_1519'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'letter')},
        ),
    ]
